### ISSUE TITLE
Location of sWGS specific code mentioned in Supplementary Methods

### ISSUE THREAD

**Issue by lbeltrame** [markowetzlab/Drews2022_CIN_Compendium#1]
Hello,

On page 34 of the Supplementary Methods, there is a reference to the sWGS copy number fitting method:

"After the profile was segmented, we searched the space of combinations of realistic purity and ploidy values (0.01<purity<1,
1.5<average tissue ploidy<5, and tumour ploidy<5) to fit the logR to integer values, solving the logR equation for each segment:"

It is unclear if this part of the method is available in one of the repositories. Am I correct in saying it is part of QDNAseqmod? I can't confirm that myself because the source code is not available (https://github.com/markowetzlab/CINSignatureSWGSBinsize/issues/1).

The reason for this question is that I want to apply the method described in the paper to an internal sWGS dataset. I already calculated purity- and ploidy-adjusted copy numbers for those samples, but I would like to see, when extracting signatures, if the method described in the paper, when applied to our data, performs better or worse than the one I used.

**Comment by Phil9S** [comment]
Hi,

So this sWGS methodology on page 34 was performed in collaboration with the Van loo lab using [ascat.sc](https://github.com/VanLoo-lab/ASCAT.sc) which is an implementation of ASCAT for non-standard inputs (sWGS, methylation, etc.).

The use of the [SWGSBinsize](https://github.com/markowetzlab/CINSignatureSWGSBinsize) repository is not as a fully implemented sWGS pipeline but was used to establish the corresponding bin sizes and required read down sampling targets of TCGA/PCAWG WGS samples to replicate the gold standard array data, so in this instance it is probably not what you would want to use for your sWGS samples. 

While the package is public you should probably raise an issue with the ASCAT.sc authors and reference this issue if you want to specifically use the pipeline they used for that analysis.

**Comment by lbeltrame** [comment]
Thanks. I actually had the same problem (determining purity/ploidy for sWGS data) and I ended up doing something else altogether, but I'll take a look at ascat.sc and see if it fares better than what I did.
