### ISSUE TITLE
Signature name mapping

### ISSUE THREAD

**Issue by BastienNguyen** [markowetzlab/Drews2022_CIN_Compendium#2]
My understanding is that the signatures named "CS" do not correspond to the "CX" present in the paper.
Some code in https://gitfront.io/r/user-9032396/110990505bc9a8d7f7d92a7bebe0165007f21254/CNSigs-DrugCorrelations/ provide mapping for 13 signatures but not all.

Could you please provide the full mapping?
Thanks

**Comment by gmaci** [comment]
The gitfront links in the repository are obsolete and were for manuscript review purposes only. I have now fixed the links to point to the correct repositories. The correct repository for the link you have highlighted is: https://github.com/macintyrelab/CINSignatureBiomarkerAnalysis

**Comment by Martingales** [comment]
If there should still be an older file with the obsolete CS names in one of the repos, you can map the names by using this file:

[Conversion_table_new_names.txt](https://github.com/markowetzlab/Drews2022_CIN_Compendium/files/9003150/Conversion_table_new_names.txt)
