### ISSUE TITLE
Minimum copy number variants to call signatures

### ISSUE THREAD

**Issue by tetsy2** [markowetzlab/Drews2022_CIN_Compendium#5]
Hello,

I have 43 samples where we have WGS. However, I can only get signatures from 11/43 (the ones having more CNA called). Is there a minimum of CNA to use quantifyCNSignatures ? I try the example data and everything works fine.

Thanks

**Comment by Phil9S** [comment]
Hello,

Thank you for opening an issue. This is an expected behavior, please see this [markowetzlab/CINSignatureQuantification#10](https://github.com/markowetzlab/CINSignatureQuantification/issues/10)
