### ISSUE TITLE
Absolute copy number calculation

### ISSUE THREAD

**Issue by tetsy2** [markowetzlab/Drews2022_CIN_Compendium#6]
Hello,

The data table I have from CNA for my samples have the following format:

Case | Chr | Start | End | Number_copies_1_Allele | Number_copies_2_Allele | Fraction_tumoral_cells | 
M001 | 3 | 118373137 | 197840227 | 3 | 1 | 0.66| 

Can this be inputed in the pipeline quantifyCNSignatures?  Is there any log2 transformation needed? If that is the case, how should we treat the loss in homozygsis? I guess that the resulting number should be multiplied by the Fraction_tumoral_cells, right? Sorry for the questions, but I find the information about the input data (even the description of the TCGA example) very scarce.

Thanks,
Robert

**Comment by Phil9S** [comment]
Hello,

For your given input, you would need to combine the two alleles into a total copy number count. The copy number signatures method does not currently utilise allele-specific information. With regards to normalising by tumour fraction, I can not say that you would need to adjust by the given purity without knowing your analysis pipeline, though typically copy numbers are given after correction for the tumour fraction as this is the proportion that most researchers would care about.

I would advise using the [markowetzlab/CINSignatureQuantification](https://github.com/markowetzlab/CINSignatureQuantification/) package to perform the copy number signature analysis which has reasonably good documentation for the input format and error catching for incorrectly formatted data.
